sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "stable"
script:
  - npm run test
  - npm run check-coverage
  - npm run build
after_success:
  - npm run semantic-release