sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "stable"
before_install:
  - npm i -g npm@^3.0.0
script:
  - npm run test
  - npm run build